/****************************
Generated by SpotDev.
********************************/
var sp = getSpotifyApi(1);
var models = sp.require("sp://import/scripts/api/models");
var views = sp.require("sp://import/scripts/api/viweas");
var ui = sp.require("sp://import/scripts/api/ui");
var pager = sp.require("sp://import/scripts/api/ui");

exports.init = init;
/*********
Init function
************/
function init() {
	/*
	Write your actions here
	*/
}