//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotDev.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpotDev.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Header {
            get {
                object obj = ResourceManager.GetObject("Header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ic_file_js32x32 {
            get {
                object obj = ResourceManager.GetObject("ic_file_js32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///Generated by SpotDev.
        ///Copyright (C) ${Year} ${App.Author}
        ///--&gt;
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;${App.Title}&lt;/title&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; href=&quot;css/stylesheet.css&quot; type=&quot;text/css&quot; /&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; href=&quot;sp://import/stylesheet/api.css&quot; type=&quot;text/css&quot;/&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; href=&quot;sp://import/stylesheet/${App.Theme}.css&quot; type=&quot;text/css&quot;/&gt;
        ///		&lt;script src=&quot;script.js&quot; type=&quot;text/javascript&quot; language=&quot;javascript&quot;&gt;&lt;/script&gt;
        ///	&lt;/head&gt;
        ///	&lt;body onload=&quot;sp = getSpotifyApi(1); sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index_html {
            get {
                return ResourceManager.GetString("index_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /********************
        ///Auto-generated manifest.json for the spotify apps project &apos;$(App)&apos;
        ///********************/
        ///{
        ///	&quot;BundleType&quot;: &quot;Application&quot;,
        ///	&quot;AppName&quot;: {
        ///			&quot;en&quot; : &quot;${App.title}&quot;
        ///	}
        ///	&quot;SupportedLanguages&quot;:[
        ///		&quot;en&quot;
        ///	],
        ///	&quot;AcceptedLinkTypes&quot;:[
        ///		&quot;artist&quot;, &quot;playlist&quot;, &quot;track&quot;, &quot;user&quot;
        ///	],
        ///	&quot;AppDescription&quot;:{
        ///		&quot;en&quot;:&quot;${App.Description}&quot;
        ///	},
        ///	&quot;AppURL&quot;: &quot;${App.Url}&quot;,
        ///	&quot;BundleCopyright&quot;:&quot;(C) ${Year} ${App.Author}&quot;,
        ///	&quot;AppIcon&quot;:{	
        ///		&quot;36x18&quot; :&quot;${App.BundleIdentifier}.png&quot;
        ///	},
        ///	&quot;BundleVersion&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manifest_json {
            get {
                return ResourceManager.GetString("manifest_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****************************
        ///Generated by SpotDev.
        ///Copyright (C) ${Year} ${App.Author}
        ///********************************/
        ///var sp = getSpotifyApi(1);
        ///var models = sp.require(&quot;sp://import/scripts/api/models&quot;);
        ///var views = sp.require(&quot;sp://import/scripts/api/viweas&quot;);
        ///var ui = sp.require(&quot;sp://import/scripts/api/ui&quot;);
        ///var pager = sp.require(&quot;sp://import/scripts/api/ui&quot;);
        ///
        ///exports.init = init;
        ///
        ////*********
        ///Init function
        ///************/
        ///function init() {
        ///	/*
        ///	Write your actions here
        ///	*/
        ///	
        ///	// In [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script_js {
            get {
                return ResourceManager.GetString("script_js", resourceCulture);
            }
        }
    }
}
